#!/bin/bash
#THIS SCRIPT UPGRADES JAVA!!!!

#PROMPT USER ON UPDATING JAVA OR NOT
echo "WOULD YOU LIKE TO UPDATE YOUR JAVA VERSION? PLEASE TYPE YES OR NO TO CONTINUE. "
read USERINPUT
if [ "$USERINPUT" == "YES" ] || [ "$USERINPUT" == "yes" ]; then 
  echo "OK INSTALLING NEW VERSION OF JAVA NOW..."
  echo "========================================"
  
#UPDATE YUM REPO
sudo yum update -y
 
#INSTALL JAVA JDK 11
sudo yum install java-ll-open-devel -y
sudo yum install java-11-openjdk -y 
 
#SET DEFAULT JAVA VERSION
echo "REMOVING OLD JAVA 8 SYMLINK...."
sudo unlink /usr/lib/jvm/java

echo "LINKING NEW JAVA...."
echo "===================="
sudo ln -s /usr/lib/jvm/new_java /usr/lib/jvm/java

echo "UPDATING ALTERNATIVES FOR JAVA AND JAVA COMPILER"
echo "================================================"
sudo update-alternatives --set java /usr/lib/jvm/new_java/bin/java
sudo update-alternatives --set javac /usr/lib/jvm/new_java/bin/javac

echo "YOU ARE NOW SET YOUR CURRENT VERSION IS........"
echo "==============================================="
#CHECK VERSION
java -version
 
elif
 [ "$USERINPUT" == "NO" ] || [ "$USERINPUT" == "no" ]; then
  echo "OK ENJOY THE REST OF YOUR DAY. "
else
  echo "YOU DID NOT FOLLOW DIRECTIONS...GOODBYE!!!!"
fi
